# Homework set 2

Please **submit this Jupyter notebook through Canvas** no later than **Mon Nov. 14, 9:00**. **Submit the notebook file with your answers (as .ipynb file) and a pdf printout. The pdf version can be used by the teachers to provide feedback. A pdf version can be made using the save and export option in the Jupyter Lab file menu.**

Homework is in **groups of two**, and you are expected to hand in original work. Work that is copied from another group will not be accepted.

# Exercise 0
Write down the names + student ID of the people in your group.

Run the following cell to import some packages, add additional packages yourself when needed.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Exercise 1

## (a) 1 point
Let $A$ be the matrix $\begin{bmatrix} 1 & -1 & \alpha \\ 2 & 2 & 1 \\ 0 & \alpha & -3/2 \end{bmatrix}$. For which values of $\alpha$ is $A$ singular?

YOUR ANSWER HERE

## (b) 1 point
For the largest value of $\alpha$ you found above, find a nonzero vector $b$ such that $Ax = b$ has infinitely many solutions. Explain your answer.

YOUR ANSWER HERE

# Exercise 2

For solving linear systems such as $Ax = b$, it is unnecessary (and often unstable) to compute the inverse $A^{-1}$. Nonetheless, there can be situations where it is useful to compute $A^{-1}$ explicitly. One way to do so is by using the LU-decomposition of $A$.

## (a) 2 points
Write an algorithm to compute $A^{-1}$ for a non-singular matrix $A$ using its LU-decomposition. You can use `scipy.linalg.lu` (which returns an LU-decomposition with _partial pivoting_, i.e., with a permutation matrix $P$) and the other `scipy.linalg.lu_*` functions, but not `scipy.linalg.inv` (or other methods for computing matrix inverses directly).

(Make sure to import the necessary functions/packages.)

In [163]:
import scipy as sp
import scipy.linalg as sla

def gaussElim(a,b):
    n = len(b)
    # Elimination phase
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                #if not null define λ
                lam = a [i,k]/a[k,k]
                #we calculate the new row of the matrix
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                #we update vector b
                b[i] = b[i] - lam*b[k]
                # backward substitution
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    
    return b


def invert(A):
    '''invert the matrix A'''
    n = len(A)
    
    temp = sla.lu(A)
    L, U = temp[1], temp[2]
    
    I = np.identity(n)
    
    res = []
    for i in range(n):
        d = sla.solve(L, I[i])
        d.shape = (n, 1)
        if i == 0:
            res = sla.solve(U, d)
        else:
            res = np.hstack((res, sla.solve(U, d)))
        
    return  res

M = [[1, 2, 0, 1, 0], [1, 1, 0, 1, 1], [0, 1, 1, 0, 0], [2, 3, 0, 1, 4], [1, 1, 0, 1, 3]]

M = np.random.randint(4, size=(8,8))

print(np.array(M), '\n')
print(invert(M), '\n')
print(sla.inv(M), '\n')

print(np.matmul(M, invert(M)).round(1), '\n')
print(np.matmul(M, sla.inv(M)).round(1))

[[1 2 2 3 0 3 3 1]
 [1 0 2 3 3 0 2 2]
 [2 3 3 1 3 0 3 2]
 [2 1 3 2 2 1 1 2]
 [0 1 3 2 2 3 2 0]
 [1 2 0 0 2 3 2 2]
 [2 3 3 0 3 0 1 3]
 [0 1 3 2 3 0 2 2]] 

[[ 0.34302326  0.48837209 -0.06104651 -0.15406977  0.01453488  0.05232558
  -0.2877907  -0.38953488]
 [-0.5        -1.5         0.5         0.5         1.         -0.5
   1.5        -1.        ]
 [ 0.27325581  0.87209302 -0.17151163 -0.19476744 -0.84011628  0.0755814
  -0.66569767  0.71511628]
 [-0.56976744 -1.11627907  0.38953488  0.45930233  1.14534884 -0.47674419
   1.12209302 -0.89534884]
 [-0.16860465 -0.69767442  0.4622093  -0.11918605  0.74709302 -0.11046512
   0.60755814 -0.62209302]
 [-0.11046512  0.23255814  0.09593023 -0.04360465 -0.16569767  0.20348837
  -0.11918605  0.04069767]
 [ 0.74418605  0.90697674 -0.48837209 -0.23255814 -0.88372093  0.41860465
  -1.30232558  0.88372093]
 [-0.08139535  0.69767442 -0.5872093  -0.00581395 -0.62209302  0.36046512
  -0.48255814  0.87209302]] 

[[-0.15406977  0.01453488  0.34302326  0.4

## (b) 1 point
What is the computational complexity of your algorithm, given that the input matrix has size $n \times n$?
Give a short calculation/explanation for your answer.

YOUR ANSWER HERE

# Exercise 3

## (a) (2 points) 
What happens when Gaussian elimination with partial pivoting is used on a matrix of the following form?
$$
  \begin{bmatrix}
     1 &  0 &  0 &  0 &  1 \\
    -1 &  1 &  0 &  0 &  1 \\
    -1 & -1 &  1 &  0 &  1 \\
    -1 & -1 & -1 &  1 &  1 \\
    -1 & -1 & -1 & -1 &  1 
  \end{bmatrix}
$$
Do the entries of the transformed matrix grow? What happens if complete pivoting is used instead? (Note that part (a) does not require a computer.)


YOUR ANSWER HERE

## (b) (2 points)
Write a method that generates a matrix of the form of part (a) of size $n \times n$ for any $n$. Use a library routine for Gaussian elimination with partial pivoting to solve various sizes of linear systems of this form, using right-hand-side vectors chosen so that the solution is known. Try for example the case where the true solution is a vector of uniformly distributed random numbers between 0 and 1. How do the error, residual, and condition number behave as the systems become larger? Comment on the stability (see chapter 1) of Gaussian elimination with partial pivoting in this case.

N.B. This is an artificially contrived system that does not reflect the behavior of Gaussian elimination in realistic examples.

In [172]:
import numpy as np

def gen(n):
    M = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            if j < i:
                M[i][j] = -1
            elif j == i or j == n-1:
                M[i][j] = 1
    return M

In [174]:
print(gen(5))

[[ 1.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  1.]
 [-1. -1.  1.  0.  1.]
 [-1. -1. -1.  1.  1.]
 [-1. -1. -1. -1.  1.]]


In [ ]:
def gaussElim(a,b):
    n = len(b)
    # Elimination phase
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                #if not null define λ
                lam = a [i,k]/a[k,k]
                #we calculate the new row of the matrix
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                #we update vector b
                b[i] = b[i] - lam*b[k]
                # backward substitution
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    
    return b

In [181]:
A = np.array([[1, 0, 1], [1, 1, 0], [0, 1, 0]])
b = np.array([1, 2, 3])
print(gaussElim(A, b))
print(sla.solve(A, b))


[-1  3  2]
[-0.33333333  2.66666667 -0.66666667]
